version: "3.8"

volumes:
  legendary-motorsport-db:

services:
  marketplace-app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "db:postgres"
    ports: 
      - 8080:8080
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - legendary-motorsport-db:/var/lib/postgresql/data
