version: "3.8"

volumes:
  legendary-motorsport-db:

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - legendary-motorsport-db:/var/lib/postgresql/data
